### PR TITLE
Copy dockerfiles from src-d/infra-science

### PR DESCRIPTION
**Pull request by vmarkovtsev**
Signed-off-by: Vadim Markovtsev <vadim@sourced.tech>

### CODE REVIEW

**Comment by rporres** [comment]
Apologies for having overviewed this. This makes total sense to avoid multiple repos containing Dockerfiles

A few comments:

* This repo has a very simple Travis job to build images on merge. That means it expects a certain structure for the dockerfiles. See https://github.com/src-d/infrastructure-dockerfiles/tree/master/git-server as an example. As you can see:
  * Directory name must be the image name
  * A `VERSION` file must be included
  * A `Makefile` referring to the main [`Makefile.main`](https://github.com/src-d/infrastructure-dockerfiles/blob/master/Makefile.main) must be included
* We should also add to MAINTAINERS a person from the ML team for these images and `spark-ml`

**Comment by vmarkovtsev** [comment]
I am here, I plan to work on this tomorrow

**Comment by vmarkovtsev** [comment]
@rporres is it good now?

**Comment by rporres** [comment]
Looks great, thx. Two details:

* `MAINTAINERS` file should be updated stating that these new files plus `spark-ml` are maintained by someone in the ML team and the rest by the current maintainers.
* there are empty `dive.log` files. Do we need them?

A detail worth to mention is that travis job does not push a `latest` tag. It should be easy to add in case you want it.

**Comment by vmarkovtsev** [comment]
Done.

Yes, we need the `latest` tag because they are used by JupyterHub.

**Comment by vmarkovtsev** [comment]
@rporres ping

**Comment by rporres** [comment]
> Yes, we need the latest tag because they are used by JupyterHub.

Then we should add that into [`Makefile.main`](https://github.com/src-d/infrastructure-dockerfiles/blob/master/Makefile.main) as part of this PR so that they are built and `latest` image corresponds with higher semver version image

I've added that into your fork via https://github.com/vmarkovtsev/infrastructure-dockerfiles/pull/1. Please review it and merge it there and we should be ready

**Comment by rporres** [comment]
I've made a local copy of the images that will be overwritten by this PR in case we need them

**Pull request merged**
